# Default values for cp_eks.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
cp_eks:
  namespace: 7a9da14a-977c-4100-988e-91867007a3b4
  providerConfigName: 95c3bbf8-10ce-4d12-a837-8bd1173dfc84

  eks:
    name: dev
    region: us-west-1
    version: "1.23"
    endpointPrivateAccess: false
    endpointPublicAccess: true

  network:
    subnetIds:
    - "subnet-0d566919bd05153ea"
    - "subnet-0f3dba0dc84350eb7"
    - "subnet-09f04e7e7ac1843de"

  nodeGroups:
    - name: ngmgm
      minSize: 3
      maxSize: 3
      desiredSize: 3
      instanceTypes:
      - m5.large
      amiType: AL2_x86_64
      capacityType: SPOT
      labels:
        nodegroup: management
        env: dev
